import {StyleSheet} from 'react-native';

export const DashboardStyle = StyleSheet.create({
  dashboard: {
    backgroundColor: '#F9F9F9',
    flex: 1,
    position: 'relative',
    alignItems: 'center',
    paddingHorizontal: 30,
  },
  dashboardContent: {
    width: '100%',
    marginTop: 5,
  },
  storename: {
    letterSpacing: 1,
    fontSize: 20,
    color: '#000',
    fontFamily: 'Quicksand-SemiBold',
  },
  storebranch: {
    marginBottom: 5,
  },
  dashBTitleSearchB: {
    alignItems: 'center',
  },
  dashboardTitle: {
    fontSize: 25,
    color: '#000',
    fontFamily: 'Quicksand-SemiBold',
    marginBottom: 10,
  },
  searchbar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    height: 35,
    borderRadius: 10,
    width: '35%',
    borderWidth: 0.5,
    borderColor: '#E6E6E6',
  },
  searchInput: {
    backgroundColor: '#fff',
    color: '#000',
    left: 10,
    height: 30,
    borderRadius: 10,
    fontSize: 14,
    width: '90%',
    paddingLeft: 8,
    padding: 0,
    fontFamily: 'Quicksand-Medium',
  },
  SearchIcon: {
    fontSize: 18,
    left: 10,
    color: '#B1B1B1',
  },
  overAll: {
    backgroundColor: '#DB1B1B',
    borderRadius: 8,
    width: '100%',
    height: 60,
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  overAllContent: {
    top: 5,
    alignItems: 'center',
  },
  overAllText: {
    color: '#fff',
    fontSize: 15,
    fontFamily: 'Quicksand-SemiBold',
  },
  overAllValue: {
    color: '#fff',
    fontWeight: 900,
    fontSize: 18,
    top: 2,
  },
  summaryRevenue: {
    flexDirection: 'row',
    top: 10,
    justifyContent: 'space-between',
  },
  orderSummaryReven: {
    width: '49%',
    backgroundColor: '#fff',
    shadowColor: '#000',
    elevation: 5,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 15,
  },
  titleFil: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  title: {
    fontFamily: 'Quicksand-Bold',
    fontSize: 15,
    color: '#000',
  },
  filterDate: {
    flexDirection: 'row',
    top: -10,
  },
  forgotBtn: {
    alignItems: 'flex-end',
    marginTop: -15,
  },
  textBtnOpacity: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  filterText: {
    fontSize: 14,
    color: '#464646',
    justifyContent: 'center',
    fontFamily: 'Quicksand-Medium',
  },
  border: {
    color: '#464646',
    fontSize: 24,
    margin: 2,
  },
  newOrder: {
    width: '100%',
    backgroundColor: '#DB1B1B',
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 15,
    borderRadius: 10,
  },
  newOrderText: {
    fontFamily: 'Quicksand-SemiBold',
    color: '#fff',
    fontSize: 15,
  },
  manageText: {
    fontSize: 14,
    color: '#fff',
    justifyContent: 'center',
    fontFamily: 'Quicksand-SemiBold',
  },
  OrderDetails: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingBottom: 10,
    paddingTop: 10,
    borderRadius: 10,
  },
  preparing: {
    backgroundColor: '#4285F4',
    width: '30%',
    alignItems: 'center',
    borderRadius: 10,
    padding: 10,
  },
  served: {
    backgroundColor: '#12BF38',
    width: '30%',
    alignItems: 'center',
    borderRadius: 10,
    padding: 10,
  },
  cancelled: {
    backgroundColor: '#777777',
    width: '30%',
    alignItems: 'center',
    borderRadius: 10,
    padding: 10,
  },
  orderTotal: {
    color: '#fff',
    fontSize: 18,
    fontFamily: 'Quicksand-SemiBold',
  },
  orderText: {
    color: '#fff',
    fontSize: 14,
    fontFamily: 'Quicksand-SemiBold',
  },
  categoryRevenue: {
    top: -10,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  catRevenBtns: {
    alignItems: 'center',
    justifyContent: 'center',
    width: '24%',
    height: 35,
    backgroundColor: '#B1B1B1',
  },
  Revenue: {
    alignItems: 'center',
    fontSize: 12,
    color: '#FFF',
    justifyContent: 'center',
    fontFamily: 'Quicksand-SemiBold',
  },
});
