import {StyleSheet} from 'react-native';

export const InventoryStyle = StyleSheet.create({
  inventContainer: {
    backgroundColor: '#F9F9F9',
    flex: 1,
    position: 'relative',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  inventContent: {
    width: '100%',
    top: 10,
  },
  inventTitle: {
    fontSize: 20,
    color: '#000',
    fontFamily: 'Quicksand-Bold',
  },
  inventTable: {
    justifyContent: 'flex-start',
    backgroundColor: '#fff',
    shadowColor: '#000',
    elevation: 5,
    borderRadius: 5,
    width: '100%',
    height: 250,
    top: 10,
  },
  idCell: {
    width: 50,
    textAlign: 'center',
  },
  productNameCell: {
    width: 250,
    fontSize: 16,
  },
  wtQtyCell: {
    width: 60,
    textAlign: 'center',
  },
  typeRW: {
    width: 70,
    textAlign: 'center',
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderColor: '#909090',
    padding: 1,
  },
  cellHeader: {
    paddingVertical: 10,
    color: '#000',
    fontFamily: 'Quicksand-Bold',
  },
  cell: {
    fontSize: 14,
    paddingTop: 10,
    color: '#303030',
    fontFamily: 'Quicksand-SemiBold',
  },
  columnWidth: {
    flex: 1,
    minWidth: 120,
    padding: 8,
  },
  inventformCon: {
    width: '100%',
  },
  form: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  DropdownContainer: {
    width: '18%',
  },
  dropdown: {
    backgroundColor: 'white',
    borderColor: '#E6E6E6',
    height: 34,
    shadowColor: '#000',
    elevation: 5,
    borderRadius: 8,
    paddingHorizontal: 8,
    marginBottom: 10,
    width: '100%',
  },
  label: {
    position: 'absolute',
    backgroundColor: 'white',
    left: 22,
    top: 8,
    zIndex: 999,
    paddingHorizontal: 8,
    fontSize: 14,
  },
  placeholderStyle: {
    fontSize: 15,
    color: '#000',
    fontFamily: 'Quicksand-Medium',
  },
  selectedTextStyle: {
    color: '#000',
    fontSize: 14,
    fontFamily: 'Quicksand-SemiBold',
  },
  iconStyle: {
    width: 20,
    height: 20,
  },
  inputSearchStyle: {
    height: 40,
    fontSize: 80,
    color: '#000',
  },

  inventoryInput: {
    width: '35%',
    fontSize: 15,
    height: 35,
    padding: 8,
    backgroundColor: '#fff',
    borderRadius: 8,
    marginBottom: 10,
    shadowColor: '#000',
    elevation: 5,
    color: '#000',
    fontFamily: 'Quicksand-SemiBold',
  },
  netWtQtyInput: {
    width: '14%',
    fontSize: 15,
    height: 35,
    padding: 8,
    backgroundColor: '#fff',
    borderRadius: 8,
    marginBottom: 10,
    shadowColor: '#000',
    elevation: 5,
    color: '#000',
    fontFamily: 'Quicksand-SemiBold',
  },
  addInvetoryOpacity: {
    width: '15%',
    height: 35,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#4285F4',
    borderRadius: 10,
    flexDirection: 'row',
  },
  addInventTextBtn: {
    fontSize: 15,
    color: 'white',
    justifyContent: 'center',
    fontFamily: 'Quicksand-Bold',
  },
  invetoryFilter: {
    flexDirection: 'row',
  },
  invetoryBtnAll: {
    marginLeft: 5,
    width: 60,
    height: 25,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#DB1B1B',
    borderRadius: 3,
    flexDirection: 'row',
  },
  invetoryBtn: {
    marginLeft: 5,
    width: 120,
    height: 25,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#DB1B1B',
    borderRadius: 3,
    flexDirection: 'row',
  },
  filterTextBtn: {
    fontSize: 13,
    color: 'white',
    justifyContent: 'center',
    fontFamily: 'Quicksand-Bold',
  },
  manageBtnOpacity: {
    justifyContent: 'center',
    alignItems: 'center',
    height: 30,
    width: 30,
  },
  itemBtn: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: 70,
  },
  centeredViewModal: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalView: {
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 10,
    height: 200,
    width: 250,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },

  dropdownModal: {
    width: '90%',
    alignItems: 'center',
  },

  modalButton: {
    borderRadius: 8,
    padding: 5,
    marginTop: 10,
    elevation: 2,
    width: 100,
    backgroundColor: '#2196F3',
  },
  btnText: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  modalText: {
    fontSize: 14,
    marginBottom: 15,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  qtyContainer: {
    width: 100,
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F6F6F8',
    height: 35,
    borderRadius: 5,
  },
  input: {
    textAlign: 'center',
    color: '#000',
    fontSize: 15,
    fontFamily: 'Quicksand-Bold',
  },
});

export const CategoryInventoryStyle = StyleSheet.create({
  row: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderColor: '#909090',
    padding: 1,
  },

  noWidth: {
    width: 50,
    textAlign: 'left',
    padding: 10,
  },
  catName: {
    textAlign: 'left',
    minWidth: 400,
    padding: 10,
  },
  textCell: {
    marginTop: 5,
    color: '#000',
    fontSize: 15,
    fontFamily: 'Quicksand-SemiBold',
  },
  container: {
    backgroundColor: '#F9F9F9',
    flex: 1,
    position: 'relative',
    alignItems: 'center',
    paddingHorizontal: 30,
  },
  content: {
    width: '100%',
    position: 'absolute',
    top: 15,
  },
  title: {
    fontSize: 20,
    color: '#000',
    fontFamily: 'Quicksand-SemiBold',
    marginBottom: 5,
  },
  input: {
    width: '40%',
    fontSize: 15,
    height: 35,
    padding: 10,
    backgroundColor: '#fff',
    borderRadius: 8,
    marginBottom: 10,
    shadowColor: '#000',
    elevation: 5,
    color: '#000',
    fontFamily: 'Quicksand-SemiBold',
  },
  saveBtn: {
    backgroundColor: '#4285F4',
    width: 100,
    height: 35,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 10,
  },
  btnText: {
    fontSize: 15,
    color: '#fff',
    fontFamily: 'Quicksand-Meduim',
  },
  tableWidth: {
    backgroundColor: '#fff',
    shadowColor: '#000',
    borderRadius: 5,
    elevation: 5,
    width: '100%',
    height: 280,
    marginTop: -5,
  },
  textHeader: {
    color: '#000',
    fontSize: 15,
    fontFamily: 'Quicksand-Bold',
  },
  horContainer: {
    flexDirection: 'row',
  },
});
