/* eslint-disable prettier/prettier */
import {StyleSheet} from 'react-native';

export const addMenuStyle = StyleSheet.create({
  addMenuContainer: {
    backgroundColor: 'rgba(20, 20, 22, 0.5)',
    position: 'absolute',
    justifyContent: 'flex-start',
    borderRadius: 20,
    top: 60,
    height: 330,
    width: 680,
  },
  newMenuText: {
    left: 30,
    color: '#42e991',
    fontSize: 18,
    fontWeight: 500,
  },
  fieldsrow1Img: {
    flexDirection: 'row',
  },
  textFields: {
    flexDirection: 'column',
    left: 15,
    position: 'absolute',
    top: 25,
  },
  fieldsrow1: {
    flexDirection: 'row',
  },
  imgContainer: {
    backgroundColor: 'red',
    justifyContent: 'center',
    left: 100,
    width: 200,
    height: 60,
  },
  fieldsrow2: {
    top: 10,
  },
  fieldsrow3: {
    flexDirection: 'row',
    top: 15,
  },
  inputName: {
    backgroundColor: 'white',
    height: 25,
    width: 180,
    fontSize: 10,
    borderWidth: 1,
    padding: 5,
    borderRadius: 10,
  },
  inputTime: {
    height: 25,
    width: 80,
    fontSize: 10,
    // borderWidth: 1,
    padding: 5,
    // backgroundColor: 'white',
    borderRadius: 10,
  },
  inputTimer: {
    backgroundColor: 'white',
    flexDirection: 'row',
    left: 10,
    height: 25,
    width: 100,
    borderRadius: 10,
  },
  timerIcon: {
    left: -8,
    top: 2,
  },
  description: {
    textAlignVertical: 'top',
    backgroundColor: 'white',
    height: 50,
    width: 290,
    fontSize: 10,
    borderWidth: 1,
    padding: 5,
    borderRadius: 15,
  },
  AvailDropdown: {
    backgroundColor: 'white',
    left: 10,
    width: 100,
    height: 25,
    borderWidth: 0.5,
    borderRadius: 8,
    paddingHorizontal: 8,
  },
  categoryDropdown: {
    left: 2,
    backgroundColor: 'white',
    borderColor: 'gray',
    width: 180,
    height: 25,
    borderWidth: 0.5,
    borderRadius: 8,
    paddingHorizontal: 8,
  },
  icon: {
    marginRight: 5,
  },
  label: {
    backgroundColor: 'white',
    position: 'absolute',
    left: 22,
    top: 8,
    zIndex: 999,
    paddingHorizontal: 8,
    fontSize: 10,
  },
  placeholderStyle: {
    fontSize: 10,
  },
  selectedTextStyle: {
    color: '#42e991',
    fontSize: 10,
  },
  iconStyle: {
    width: 20,
    height: 20,
  },
  inputSearchStyle: {
    height: 40,
    fontSize: 10,
  },
  ingredientContainer: {
    backgroundColor: 'rgba(50,49,47, 0.5)',
    alignItems: 'flex-start',
    justifyContent: 'center',
    position: 'absolute',
    top: 125,
    width: 620,
    height: 95,
  },
  ingredienText: {
    color: '#fff',
    left: 15,
    top: 0,
  },
  ingredientContent: {
    backgroundColor: '#979797',
    left: 10,
    top: 0,
    width: 600,
    height: 60,
    borderRadius: 10,
  },
  addOns: {
    justifyContent: 'space-around',
    flexDirection: 'row',
    position: 'absolute',
    top: 225,
    left: 40,
  },
  addOnsDropdown: {
    backgroundColor: 'white',
    borderColor: 'gray',
    left: 2,
    width: 150,
    height: 25,

    borderWidth: 0.5,
    borderRadius: 8,
    paddingHorizontal: 8,
  },
  bottomTextfield: {
    flexDirection: 'row',
    left: 70,
  },
  textInput: {
    backgroundColor: 'white',
    height: 25,
    width: 150,
    fontSize: 10,
    borderWidth: 1,
    padding: 5,
    borderRadius: 10,
    left: 10,
  },
  btnContainer: {
    justifyContent: 'flex-end',
    flexDirection: 'row',
    top: 310,
    left: 365,
    position: 'absolute',
  },
  //-----
  btnCancelOpacity: {
    width: 130,
    height: 30,
    shadowColor: 'blue',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
    backgroundColor: '#979183',
    top: -60,
  },
  btnCSaveOpacity: {
    width: 130,
    height: 30,
    shadowColor: 'blue',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
    backgroundColor: '#EEA734',
    top: -60,
  },
  cancelBtn: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 15,
    left: -28,
  },
  saveBtn: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 15,
    left: -5,
  },
  textBtn: {
    fontSize: 10,
    fontWeight: 900,
    color: '#000',
    justifyContent: 'center',
  },
});
